package model;
// Generated 21 Oct, 2017 2:07:01 AM by Hibernate Tools 4.3.1



/**
 * Empid generated by hbm2java
 */
public class Empid  implements java.io.Serializable {


     private Integer id;
     private String emid;
     private String fname;
     private String lname;
     private String mnumber;

    public Empid() {
    }

    public Empid(String emid, String fname, String lname, String mnumber) {
       this.emid = emid;
       this.fname = fname;
       this.lname = lname;
       this.mnumber = mnumber;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmid() {
        return this.emid;
    }
    
    public void setEmid(String emid) {
        this.emid = emid;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getMnumber() {
        return this.mnumber;
    }
    
    public void setMnumber(String mnumber) {
        this.mnumber = mnumber;
    }




}


